name: min
on:
  workflow_call:
    inputs:
      slug:
        required: true
        type: string
      wporg-slug:
        required: true
        type: string
      has-js:
        required: false
        type: boolean
        default: false
      dry-run:
        required: false
        type: boolean
        default: false
    secrets:
      WPORG_SVN_USERNAME:
        required: false
      WPORG_SVN_PASSWORD:
        required: false
permissions:
  contents: read
jobs:
  t:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo checkout
      - run: echo setupphp
      - name: ver
        id: ver
        run: echo "version=x" >> "$GITHUB_OUTPUT"
      - if: ${{ inputs.has-js }}
        run: echo js
      - if: ${{ !inputs.dry-run }}
        run: echo "deploy ${{ secrets.WPORG_SVN_USERNAME }} ${{ inputs.wporg-slug }} ${{ steps.ver.outputs.version }}"
      - if: ${{ inputs.dry-run }}
        run: echo dryzip
      - if: ${{ !inputs.dry-run }}
        run: echo "ghrelease ${{ steps.ver.outputs.tag }}"
